database:
  user: root
  password: password
  driver: org.mysql.Driver
  host: localhost
  port: 3306
  type: mysql
  dbname : aion-web-site
mail:
  identifiant: dtigrus@gmail.com
  password: TIGRANtoine92
